/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EduSys.ui;

import EduSys.DAO.NhanVienDAO;
import EduSys.entity.NhanVien;
import EduSys.utils.Auth;
import EduSys.utils.MsgBox;

/**
 *
 * @author DMX
 */
public class DangNhapJDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form DangNhapJDiaLog
     */
    public DangNhapJDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHinhLG = new javax.swing.JLabel();
        pnlDN = new javax.swing.JPanel();
        lblTK = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        lblMk = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        ntnKT = new javax.swing.JButton();
        txtMK = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EduSys - Đăng nhập");
        setAlwaysOnTop(true);

        lblHinhLG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/Icon/LogoOK.png"))); // NOI18N

        pnlDN.setFocusTraversalPolicyProvider(true);

        lblTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTK.setForeground(new java.awt.Color(0, 0, 255));
        lblTK.setText("Tài Khoản:");

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/Icon/Tick.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        lblMk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMk.setForeground(new java.awt.Color(0, 0, 255));
        lblMk.setText("Mật Khẩu:");

        txtTK.setText("datcoi");
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });

        ntnKT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/Icon/Stop.png"))); // NOI18N
        ntnKT.setText("Kết Thúc");
        ntnKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntnKTActionPerformed(evt);
            }
        });

        txtMK.setText("123");

        javax.swing.GroupLayout pnlDNLayout = new javax.swing.GroupLayout(pnlDN);
        pnlDN.setLayout(pnlDNLayout);
        pnlDNLayout.setHorizontalGroup(
            pnlDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDNLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(pnlDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTK)
                    .addComponent(txtMK)
                    .addGroup(pnlDNLayout.createSequentialGroup()
                        .addGroup(pnlDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDNLayout.createSequentialGroup()
                                .addGroup(pnlDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTK, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(lblMk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDNLayout.createSequentialGroup()
                                .addComponent(btnDangNhap)
                                .addGap(18, 18, 18)))
                        .addComponent(ntnKT))))
        );
        pnlDNLayout.setVerticalGroup(
            pnlDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDNLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMK, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(pnlDNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntnKT)
                    .addComponent(btnDangNhap)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinhLG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHinhLG))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ntnKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntnKTActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_ntnKTActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        this.dangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDiaLog dialog = new DangNhapJDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel lblHinhLG;
    private javax.swing.JLabel lblMk;
    private javax.swing.JLabel lblTK;
    private javax.swing.JButton ntnKT;
    private javax.swing.JPanel pnlDN;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
    }
    NhanVienDAO dao = new NhanVienDAO();
    void dangNhap(){
        String manv = txtTK.getText();
        String matKhau = new String(txtMK.getPassword());
        NhanVien nv = dao.selectById(manv);
        if(manv.equals("")&&matKhau.equals("")){
            MsgBox.alert(this, "Vui lòng nhập thông tin!");
        }
        else if(nv==null){
            MsgBox.alert(this,"Sai tên đăng nhập");
        }
        else if(!matKhau.equals(nv.getMatKhau())){
            MsgBox.alert(this,"Sai mật khẩu!");
        }
        else{
            Auth.user=nv;
            this.dispose();
        }
    }
    
    void ketThuc(){
        if(MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")){
            System.exit(0);
        }
    }
}
