/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EduSys.ui;

import EduSys.DAO.ChuyenDeDAO;
import EduSys.DAO.KhoaHocDAO;
import EduSys.entity.ChuyenDe;
import EduSys.entity.KhoaHoc;
import EduSys.utils.Auth;
import EduSys.utils.ExportExcel;
import EduSys.utils.MsgBox;
import EduSys.utils.XDate;
import EduSys.utils.XImage;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
// các nút bị vô hiệu hóa bởi vì nó lấy dữ liệu bên chuyên đề
// nếu được sửa dữ liệu thì sẽ có gian dối
    
/**
 *
 * @author DMX
 */
public class KhoaHocJDialog extends javax.swing.JDialog {

    
    /**
     * Creates new form KhoaHocJDialog
     */
    public KhoaHocJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChuyenDeKH = new javax.swing.JPanel();
        cboChuyenDeKH = new javax.swing.JComboBox<>();
        tbpKhoaHoc = new javax.swing.JTabbedPane();
        pnlCapNhatKH = new javax.swing.JPanel();
        lblChuyenDe = new javax.swing.JLabel();
        lblTenChuyenDe = new javax.swing.JLabel();
        lblNgayKhaiiGiang = new javax.swing.JLabel();
        txtNgayKhaiGiang = new javax.swing.JTextField();
        lblHocPhiKH = new javax.swing.JLabel();
        lblThoiLuongKH = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblNguoiTaoKH = new javax.swing.JLabel();
        lblGhiChuKH = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtGhiChuKH = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        btnThemKH = new javax.swing.JButton();
        btnSuaKH = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnMoiKH = new javax.swing.JButton();
        btnFirstKH = new javax.swing.JButton();
        btnPrevKH = new javax.swing.JButton();
        btnNextKH = new javax.swing.JButton();
        btnLastKH = new javax.swing.JButton();
        txtHocPhiKH = new javax.swing.JTextField();
        txtThoiLuongKH = new javax.swing.JTextField();
        txtNguoiTaoKH = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        pnlDanhSachKH = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDanhSachKH = new javax.swing.JTable();
        btnExportExcel = new javax.swing.JButton();
        lblTTKhoaHoc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys - Quản lý khóa học");

        pnlChuyenDeKH.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cboChuyenDeKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChuyenDeKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChuyenDeKHLayout = new javax.swing.GroupLayout(pnlChuyenDeKH);
        pnlChuyenDeKH.setLayout(pnlChuyenDeKHLayout);
        pnlChuyenDeKHLayout.setHorizontalGroup(
            pnlChuyenDeKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cboChuyenDeKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlChuyenDeKHLayout.setVerticalGroup(
            pnlChuyenDeKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenDeKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboChuyenDeKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblChuyenDe.setText("Chuyên đề");

        lblTenChuyenDe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenChuyenDe.setForeground(new java.awt.Color(255, 0, 0));

        lblNgayKhaiiGiang.setText("Khai giảng");

        lblHocPhiKH.setText("Học phí");

        lblThoiLuongKH.setText("Thời lượng (Giờ)");

        jLabel32.setText("Ngày tạo");

        lblNguoiTaoKH.setText("Người tạo");

        lblGhiChuKH.setText("Ghi chú");

        txtGhiChuKH.setColumns(20);
        txtGhiChuKH.setRows(5);
        jScrollPane7.setViewportView(txtGhiChuKH);

        btnThemKH.setText("Thêm");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        btnSuaKH.setText("Sửa");
        btnSuaKH.setEnabled(false);
        btnSuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKHActionPerformed(evt);
            }
        });

        btnXoaKH.setText("Xóa");
        btnXoaKH.setEnabled(false);
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });

        btnMoiKH.setText("Mới");
        btnMoiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiKHActionPerformed(evt);
            }
        });

        btnFirstKH.setText("|<");
        btnFirstKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstKHActionPerformed(evt);
            }
        });

        btnPrevKH.setText("<<");
        btnPrevKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevKHActionPerformed(evt);
            }
        });

        btnNextKH.setText(">>");
        btnNextKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextKHActionPerformed(evt);
            }
        });

        btnLastKH.setText(">|");
        btnLastKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMoiKH)
                .addGap(48, 48, 48)
                .addComponent(btnFirstKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLastKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKH)
                    .addComponent(btnSuaKH)
                    .addComponent(btnXoaKH)
                    .addComponent(btnMoiKH)
                    .addComponent(btnFirstKH)
                    .addComponent(btnPrevKH)
                    .addComponent(btnNextKH)
                    .addComponent(btnLastKH))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        txtHocPhiKH.setEnabled(false);

        txtThoiLuongKH.setEnabled(false);

        txtNguoiTaoKH.setEditable(false);
        txtNguoiTaoKH.setEnabled(false);

        txtNgayTao.setEditable(false);
        txtNgayTao.setEnabled(false);

        javax.swing.GroupLayout pnlCapNhatKHLayout = new javax.swing.GroupLayout(pnlCapNhatKH);
        pnlCapNhatKH.setLayout(pnlCapNhatKHLayout);
        pnlCapNhatKHLayout.setHorizontalGroup(
            pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                        .addComponent(lblGhiChuKH, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCapNhatKHLayout.createSequentialGroup()
                        .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTenChuyenDe, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(lblChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHocPhiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNguoiTaoKH, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHocPhiKH)
                                    .addComponent(txtNguoiTaoKH))
                                .addGap(92, 92, 92)
                                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayKhaiGiang, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txtThoiLuongKH)
                                    .addComponent(txtNgayTao)
                                    .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                                        .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNgayKhaiiGiang, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblThoiLuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22))))
            .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCapNhatKHLayout.setVerticalGroup(
            pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChuyenDe)
                    .addComponent(lblNgayKhaiiGiang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayKhaiGiang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHocPhiKH)
                    .addComponent(lblThoiLuongKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHocPhiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiLuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel32))
                    .addGroup(pnlCapNhatKHLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNguoiTaoKH)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCapNhatKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNguoiTaoKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGhiChuKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpKhoaHoc.addTab("CẬP NHẬT", pnlCapNhatKH);

        tblDanhSachKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ KH", "THỜI LƯỢNG", "HỌC PHÍ", "KHAI GIẢNG", "TẠO BỞI", "NGÀY TẠO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachKHMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblDanhSachKH);

        btnExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/Icon/Excel.png"))); // NOI18N
        btnExportExcel.setText("Xuất Excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDanhSachKHLayout = new javax.swing.GroupLayout(pnlDanhSachKH);
        pnlDanhSachKH.setLayout(pnlDanhSachKHLayout);
        pnlDanhSachKHLayout.setHorizontalGroup(
            pnlDanhSachKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachKHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportExcel)
                .addGap(32, 32, 32))
        );
        pnlDanhSachKHLayout.setVerticalGroup(
            pnlDanhSachKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachKHLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportExcel)
                .addContainerGap())
        );

        tbpKhoaHoc.addTab("DANH SÁCH", pnlDanhSachKH);

        lblTTKhoaHoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTTKhoaHoc.setForeground(new java.awt.Color(255, 51, 51));
        lblTTKhoaHoc.setText("CHUYÊN ĐỀ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbpKhoaHoc)
                    .addComponent(lblTTKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlChuyenDeKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTTKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChuyenDeKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpKhoaHoc))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboChuyenDeKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChuyenDeKHActionPerformed
        // TODO add your handling code here:
        this.chonChuyenDe();
    }//GEN-LAST:event_cboChuyenDeKHActionPerformed

    private void btnFirstKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstKHActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btnFirstKHActionPerformed

    private void btnPrevKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevKHActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnPrevKHActionPerformed

    private void btnNextKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextKHActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnNextKHActionPerformed

    private void btnLastKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastKHActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnLastKHActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnSuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKHActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaKHActionPerformed

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaKHActionPerformed

    private void btnMoiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiKHActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiKHActionPerformed

    private void tblDanhSachKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachKHMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            this.row = tblDanhSachKH.getSelectedRow();
            this.edit();
            btnSuaKH.setEnabled(true);
            btnXoaKH.setEnabled(true);
            btnThemKH.setEnabled(false);
        }
    }//GEN-LAST:event_tblDanhSachKHMouseClicked

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            ExportExcel.exportTable(tblDanhSachKH);
            MsgBox.alert(this, "Lưu dữ liệu thành công");
        } catch (IOException ex) {
            MsgBox.alert(this, "Lỗi lưu trữ !");
        }
    }//GEN-LAST:event_btnExportExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhoaHocJDialog dialog = new KhoaHocJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnFirstKH;
    private javax.swing.JButton btnLastKH;
    private javax.swing.JButton btnMoiKH;
    private javax.swing.JButton btnNextKH;
    private javax.swing.JButton btnPrevKH;
    private javax.swing.JButton btnSuaKH;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.JComboBox<String> cboChuyenDeKH;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblChuyenDe;
    private javax.swing.JLabel lblGhiChuKH;
    private javax.swing.JLabel lblHocPhiKH;
    private javax.swing.JLabel lblNgayKhaiiGiang;
    private javax.swing.JLabel lblNguoiTaoKH;
    private javax.swing.JLabel lblTTKhoaHoc;
    private javax.swing.JLabel lblTenChuyenDe;
    private javax.swing.JLabel lblThoiLuongKH;
    private javax.swing.JPanel pnlCapNhatKH;
    private javax.swing.JPanel pnlChuyenDeKH;
    private javax.swing.JPanel pnlDanhSachKH;
    private javax.swing.JTable tblDanhSachKH;
    private javax.swing.JTabbedPane tbpKhoaHoc;
    private javax.swing.JTextArea txtGhiChuKH;
    private javax.swing.JTextField txtHocPhiKH;
    private javax.swing.JTextField txtNgayKhaiGiang;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNguoiTaoKH;
    private javax.swing.JTextField txtThoiLuongKH;
    // End of variables declaration//GEN-END:variables

    ChuyenDeDAO cddao = new ChuyenDeDAO();
    KhoaHocDAO dao = new KhoaHocDAO();
    private int row;
    
    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
        this.fillComboBoxChuyenDe();
        this.row=-1;
        //this.updateStatus();
    }

    private void fillComboBoxChuyenDe() {
        DefaultComboBoxModel model=(DefaultComboBoxModel)cboChuyenDeKH.getModel();
        model.removeAllElements();
        List<ChuyenDe> list = cddao.selectAll();
        for(ChuyenDe cd:list){
            model.addElement(cd);
        }
    }
      
       void fillTable(){
        DefaultTableModel model= (DefaultTableModel)tblDanhSachKH.getModel();
        model.setRowCount(0);
        try {
            ChuyenDe cd =(ChuyenDe)cboChuyenDeKH.getSelectedItem();//lấy chuyên đề được chọn trong combobox
            List<KhoaHoc> list = dao.selectByChuyenDe(cd.getMaCD());//lây sdanh sách khóa học phụ thuộc vao chuyên đề đó
            for(KhoaHoc kh : list){
                Object[] row = {kh.getMaKH(),
                                kh.getThoiLuong(),
                                kh.getHocPhi(),                             
                                XDate.toString(kh.getNgayKG(),"dd/MM/yyyy"),
                                kh.getMaNV(),
                                XDate.toString(kh.getNgayTao(), "dd/MM/yyyy")
                };
                model.addRow(row);// thêm 1 hàng vao table
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
 
    
    void chonChuyenDe(){         
        ChuyenDe chuyenDe = (ChuyenDe) cboChuyenDeKH.getSelectedItem();
        txtThoiLuongKH.setText(chuyenDe.getThoiLuong()+"");
        txtHocPhiKH.setText(chuyenDe.getHocPhi()+"");
        lblTenChuyenDe.setText(chuyenDe.getTenCD());
        txtGhiChuKH.setText(chuyenDe.getTenCD());
        
        this.fillTable();
        this.row = -1;
       // this.updateStatus();
        tbpKhoaHoc.setSelectedIndex(1);   
       
        
         
    }
  

//    private void updateStatus() {
//        boolean edit = (this.row <= 0); // người ta đang chọn hàng ở đâu đó 
//        boolean first = (this.row == 0);//đabg ở bản ghi đầu tiên
//        boolean last = (this.row == tblDanhSachKH.getRowCount() - 1);// đnag ở vị trí cuối cùng
//        // trạng thái forrm
//        btnThemKH.setEnabled(!edit);// thêm khi ko chọn hàng nào
//        btnSuaKH.setEnabled(!edit);// khi chọn hàng thì cho phép sua
//        btnXoaKH.setEnabled(!edit);//khi chọn hàng thì cho phép xoa
//
//        // trạng thái điều hương
//        btnFirstKH.setEnabled(edit && !first);// khi đang chọn hàng và ko phải hàng đầu
//        btnPrevKH.setEnabled(edit && !first);// khi đang chọn hàng và ko phải hàng đầu
//        btnNextKH.setEnabled(edit && !last);// khi đang chọn hàng và ko phải hàng cuối
//        btnLastKH.setEnabled(edit && !last);// khi đang chọn hàng và ko phải hàng cuôi      
//    }
//   
    private void first() {
        this.row = 0;
        this.edit();
//        btnFirstKH.setEnabled(false);
//        btnPrevKH.setEnabled(false);
//        btnLastKH.setEnabled(true);
//         btnNextKH.setEnabled(true);
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    private void next() {
        if (this.row < tblDanhSachKH.getRowCount() - 1) {
            this.row++;
            this.edit();
           
        }
    }

    private void last() {
        this.row = tblDanhSachKH.getRowCount() - 1;
        this.edit();
//         btnLastKH.setEnabled(false);
//         btnNextKH.setEnabled(false);
//         btnFirstKH.setEnabled(true);
//        btnPrevKH.setEnabled(true);
    }

    private void edit() {
        ChuyenDe chuyenDe = (ChuyenDe)cboChuyenDeKH.getSelectedItem();
        int makh = (Integer)tblDanhSachKH.getValueAt(this.row, 0);
        KhoaHoc kh = dao.selectById(makh);
        this.setForm(kh);
     
      //  this.updateStatus();
        tbpKhoaHoc.setSelectedIndex(0);
        lblTenChuyenDe.setText(chuyenDe.getTenCD());
        
    }

    void setForm(KhoaHoc kh){
        cboChuyenDeKH.setToolTipText(String.valueOf(kh.getMaKH()));
        cboChuyenDeKH.setSelectedItem(cddao.selectById(kh.getMaCD())); 
        txtNgayKhaiGiang.setText(XDate.toString(kh.getNgayKG(), "dd/MM/yyyy"));
        txtHocPhiKH.setText(String.valueOf(kh.getHocPhi()));
        txtThoiLuongKH.setText(String.valueOf(kh.getThoiLuong()));
        txtNguoiTaoKH.setText(kh.getMaNV());
        txtNgayTao.setText(XDate.toString(kh.getNgayTao(), "dd/MM/yyyy"));
        txtGhiChuKH.setText(kh.getGhiChu());
    }
    
     KhoaHoc getForm(){
        ChuyenDe chuyenDe = (ChuyenDe) cboChuyenDeKH.getSelectedItem();
        KhoaHoc kh = new KhoaHoc();
        kh.setMaCD(chuyenDe.getMaCD());
        kh.setNgayKG(XDate.toDate(txtNgayKhaiGiang.getText(), "dd/MM/yyyy"));
        kh.setHocPhi(Double.valueOf(txtHocPhiKH.getText()));
        kh.setThoiLuong(Integer.valueOf(txtThoiLuongKH.getText()));
        kh.setGhiChu(txtGhiChuKH.getText());
        kh.setMaNV(Auth.user.getMaNV());
        kh.setNgayTao(XDate.toDate(txtNgayTao.getText(), "dd/MM/yyyy"));
        kh.setMaKH(Integer.valueOf(cboChuyenDeKH.getToolTipText()));
        
        return kh;
    }

    private void insert() {
        
        KhoaHoc kh = getForm();
        kh.setNgayTao(new Date());
        try {
                dao.insert(kh);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this,"Thêm mới thành công!");
        } catch (Exception e) {
           e.printStackTrace();
        }
    }

    private void clearForm() {
        ChuyenDe chuyenDe = (ChuyenDe)cboChuyenDeKH.getSelectedItem();
        KhoaHoc kh = new KhoaHoc();
        kh.setMaCD(chuyenDe.getMaCD());
        kh.setMaNV(Auth.user.getMaNV());
        kh.setNgayKG(XDate.addDays(new Date(), 30));
        kh.setNgayTao(new Date());
        kh.setHocPhi(chuyenDe.getHocPhi());
        kh.setThoiLuong(chuyenDe.getThoiLuong());
        this.setForm(kh);
        this.row = -1;
        tbpKhoaHoc.setSelectedIndex(0);
       // this.updateStatus();
       btnSuaKH.setEnabled(false);
       btnXoaKH.setEnabled(false);
       btnThemKH.setEnabled(true);
    }

    private void update() {
        KhoaHoc kh = getForm();
        try {
             dao.update(kh);
                this.fillTable();
                MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    private void delete() {
           if(!Auth.isManager()){// nếu ko phải truong phong ko cho xoa
            MsgBox.alert(this,"Bạn không có quyền xóa khóa học!");
        }else{
            //String makh = .getText();         
            } if(MsgBox.confirm(this,"Bạn thực sự muốn xóa khóa học này?")){
                Integer makh = Integer.valueOf(cboChuyenDeKH.getToolTipText());
                try {
                    dao.delete(makh);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this,"Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }
    
    
    

