/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EduSys.ui;

import EduSys.DAO.NguoiHocDAO;
import EduSys.entity.NguoiHoc;
import EduSys.utils.Auth;
import EduSys.utils.ExportExcel;
import EduSys.utils.MsgBox;
import EduSys.utils.XDate;
import EduSys.utils.XImage;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;
/**
 *
 * @author DMX
 */
public class NguoiHocJDialog extends javax.swing.JDialog {

    NguoiHocDAO dao = new NguoiHocDAO();
    private int row;

    /**
     * Creates new form NguoiHocJDialog
     */
    public NguoiHocJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrGioiTinh = new javax.swing.ButtonGroup();
        lblTitleNH = new javax.swing.JLabel();
        TabbedPaneNH = new javax.swing.JTabbedPane();
        pnlCapNhatNH = new javax.swing.JPanel();
        lblMaNH = new javax.swing.JLabel();
        txtMaNH = new javax.swing.JTextField();
        lblHoVaTenNH = new javax.swing.JLabel();
        txtHoTenNH = new javax.swing.JTextField();
        lblGioiTinhNH = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblGhiCHu = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        btnThemNH = new javax.swing.JButton();
        btnSuaNH = new javax.swing.JButton();
        btnXoaNH = new javax.swing.JButton();
        btnMoiNH = new javax.swing.JButton();
        btnFirstNH = new javax.swing.JButton();
        btnPrevNH = new javax.swing.JButton();
        btnNextNH = new javax.swing.JButton();
        btnLastNH = new javax.swing.JButton();
        pnlDanhSachNH = new javax.swing.JPanel();
        pnlTimKiemNH = new javax.swing.JPanel();
        txtTimKiemNH = new javax.swing.JTextField();
        btnTimNH = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNguoiHoc = new javax.swing.JTable();
        btnExportExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys - Quản lý người học");

        lblTitleNH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitleNH.setForeground(new java.awt.Color(0, 0, 255));
        lblTitleNH.setText("QUẢN LÝ NGƯỜI HỌC");

        lblMaNH.setText("Mã người học");

        lblHoVaTenNH.setText("Họ và tên");

        lblGioiTinhNH.setText("Giới tính");

        bgrGioiTinh.add(rdoNam);
        rdoNam.setText("Nam");

        bgrGioiTinh.add(rdoNu);
        rdoNu.setSelected(true);
        rdoNu.setText("Nữ");

        lblSDT.setText("Điện thoại");

        lblNgaySinh.setText("Ngày sinh (dd/MM/yyyy)");

        lblEmail.setText("Email");

        lblGhiCHu.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane5.setViewportView(txtGhiChu);

        btnThemNH.setText("Thêm");
        btnThemNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNHActionPerformed(evt);
            }
        });

        btnSuaNH.setText("Sửa");
        btnSuaNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNHActionPerformed(evt);
            }
        });

        btnXoaNH.setText("Xóa");
        btnXoaNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNHActionPerformed(evt);
            }
        });

        btnMoiNH.setText("Mới");
        btnMoiNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiNHActionPerformed(evt);
            }
        });

        btnFirstNH.setText("|<");
        btnFirstNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstNHActionPerformed(evt);
            }
        });

        btnPrevNH.setText("<<");
        btnPrevNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevNHActionPerformed(evt);
            }
        });

        btnNextNH.setText(">>");
        btnNextNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextNHActionPerformed(evt);
            }
        });

        btnLastNH.setText(">|");
        btnLastNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastNHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMoiNH)
                .addGap(48, 48, 48)
                .addComponent(btnFirstNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLastNH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNH)
                    .addComponent(btnSuaNH)
                    .addComponent(btnXoaNH)
                    .addComponent(btnMoiNH)
                    .addComponent(btnFirstNH)
                    .addComponent(btnPrevNH)
                    .addComponent(btnNextNH)
                    .addComponent(btnLastNH))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCapNhatNHLayout = new javax.swing.GroupLayout(pnlCapNhatNH);
        pnlCapNhatNH.setLayout(pnlCapNhatNHLayout);
        pnlCapNhatNHLayout.setHorizontalGroup(
            pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatNHLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblGhiCHu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaNH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaNH, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHoVaTenNH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHoTenNH, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCapNhatNHLayout.createSequentialGroup()
                            .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGioiTinhNH, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlCapNhatNHLayout.createSequentialGroup()
                                    .addComponent(rdoNam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdoNu))
                                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(87, 87, 87)
                            .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNgaySinh)
                                .addComponent(txtEmail)
                                .addGroup(pnlCapNhatNHLayout.createSequentialGroup()
                                    .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 22, Short.MAX_VALUE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlCapNhatNHLayout.setVerticalGroup(
            pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatNHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoVaTenNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTenNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinhNH)
                    .addComponent(lblNgaySinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDT)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCapNhatNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGhiCHu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabbedPaneNH.addTab("CẬP NHẬT", pnlCapNhatNH);

        pnlTimKiemNH.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm  kiếm     "));

        btnTimNH.setText("Tìm");
        btnTimNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemNHLayout = new javax.swing.GroupLayout(pnlTimKiemNH);
        pnlTimKiemNH.setLayout(pnlTimKiemNHLayout);
        pnlTimKiemNHLayout.setHorizontalGroup(
            pnlTimKiemNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemNHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemNH, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTimNH)
                .addContainerGap())
        );
        pnlTimKiemNHLayout.setVerticalGroup(
            pnlTimKiemNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemNHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTimKiemNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemNH, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnTimNH))
                .addContainerGap())
        );

        tblNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ NH", "HỌ VÀ TÊN", "GIỚI TÍNH", "NGÀY SINH", "SĐT", "EMAIL", "MÃ NV", "NGÀY ĐĂNG KÍ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiHocMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblNguoiHoc);

        btnExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/Icon/Excel.png"))); // NOI18N
        btnExportExcel.setText("Xuất Excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDanhSachNHLayout = new javax.swing.GroupLayout(pnlDanhSachNH);
        pnlDanhSachNH.setLayout(pnlDanhSachNHLayout);
        pnlDanhSachNHLayout.setHorizontalGroup(
            pnlDanhSachNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachNHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDanhSachNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDanhSachNHLayout.createSequentialGroup()
                        .addComponent(pnlTimKiemNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachNHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportExcel)
                .addGap(47, 47, 47))
        );
        pnlDanhSachNHLayout.setVerticalGroup(
            pnlDanhSachNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachNHLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnlTimKiemNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExportExcel)
                .addContainerGap())
        );

        TabbedPaneNH.addTab("DANH SÁCH", pnlDanhSachNH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneNH)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleNH, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitleNH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TabbedPaneNH)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNHActionPerformed
        // TODO add your handling code here:
        this.timKiem();
    }//GEN-LAST:event_btnTimNHActionPerformed

    private void btnFirstNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstNHActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btnFirstNHActionPerformed

    private void btnPrevNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevNHActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnPrevNHActionPerformed

    private void btnNextNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextNHActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnNextNHActionPerformed

    private void btnLastNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastNHActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnLastNHActionPerformed

    private void tblNguoiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiHocMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount()==2){
            this.row=tblNguoiHoc.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblNguoiHocMouseClicked

    private void btnThemNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNHActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemNHActionPerformed

    private void btnSuaNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNHActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaNHActionPerformed

    private void btnXoaNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNHActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaNHActionPerformed

    private void btnMoiNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiNHActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiNHActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ExportExcel.exportTable(tblNguoiHoc);
            MsgBox.alert(this, "Lưu dữ liệu thành công");
        } catch (IOException ex) {
            MsgBox.alert(this, "Lỗi lưu trữ !");
        }
    }//GEN-LAST:event_btnExportExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NguoiHocJDialog dialog = new NguoiHocJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPaneNH;
    private javax.swing.ButtonGroup bgrGioiTinh;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnFirstNH;
    private javax.swing.JButton btnLastNH;
    private javax.swing.JButton btnMoiNH;
    private javax.swing.JButton btnNextNH;
    private javax.swing.JButton btnPrevNH;
    private javax.swing.JButton btnSuaNH;
    private javax.swing.JButton btnThemNH;
    private javax.swing.JButton btnTimNH;
    private javax.swing.JButton btnXoaNH;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhiCHu;
    private javax.swing.JLabel lblGioiTinhNH;
    private javax.swing.JLabel lblHoVaTenNH;
    private javax.swing.JLabel lblMaNH;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTitleNH;
    private javax.swing.JPanel pnlCapNhatNH;
    private javax.swing.JPanel pnlDanhSachNH;
    private javax.swing.JPanel pnlTimKiemNH;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNguoiHoc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHoTenNH;
    private javax.swing.JTextField txtMaNH;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimKiemNH;
    // End of variables declaration//GEN-END:variables

    NguoiHoc nh = new NguoiHoc();
    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
        this.fillTable();
        
        this.row = -1;
        this.updateStatus();
        this.setForm(nh);   
    }
    
    private void timKiem(){
        this.fillTable();
        this.clearForm();
        this.row=-1;
        updateStatus();
        
    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel)tblNguoiHoc.getModel();
        model.setRowCount(0);
        try {
            String key = txtTimKiemNH.getText();
            List<NguoiHoc> list = dao.selectByKeyword(key);
            for(NguoiHoc nh: list){
                  Object[] row = {nh.getMaNH(),
                                nh.getHoTen(),
                                nh.isGioiTinh()?"Nam":"Nữ",
                                XDate.toString(nh.getNgaySinh(), "dd/MM/yyyy"),
                                nh.getDienThoai(),
                                nh.getEmail(),
                                nh.getMaNV(),
                                XDate.toString(nh.getNgayDK(), "dd/MM/yyyy")
                };
                model.addRow(row);// thêm 1 hàng vao table
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

 

    private void updateStatus() {
        boolean edit = (this.row>=0); // người ta đang chọn hàng ở đâu đó 
        boolean first = (this.row==0);//đabg ở bản ghi đầu tiên
        boolean last = (this.row==tblNguoiHoc.getRowCount()-1);// đnag ở vị trí cuối cùng
        // trạng thái forrm
        txtMaNH.setEditable(!edit);// sửa khi nhập mới
        btnThemNH.setEnabled(!edit);// thêm khi ko chọn hàng nào
        btnSuaNH.setEnabled(edit);// khi chọn hàng thì cho phép sua
        btnXoaNH.setEnabled(edit);//khi chọn hàng thì cho phép xoa
        
        // trạng thái điều hương
        btnFirstNH.setEnabled(edit&&!first);// khi đang chọn hàng và ko phải hàng đầu
        btnPrevNH.setEnabled(edit&&!first);// khi đang chọn hàng và ko phải hàng đầu
        btnNextNH.setEnabled(edit&&!last);// khi đang chọn hàng và ko phải hàng cuối
        btnLastNH.setEnabled(edit&&!last);// khi đang chọn hàng và ko phải hàng cuôi
    }

    void setForm(NguoiHoc nh) {
        txtMaNH.setText(nh.getMaNH());
        txtHoTenNH.setText(nh.getHoTen());
        rdoNam.setSelected(nh.isGioiTinh());
        rdoNu.setSelected(!nh.isGioiTinh());
        txtNgaySinh.setText(XDate.toString(nh.getNgaySinh(),"dd/MM/yyyy"));
        txtSDT.setText(nh.getDienThoai());
        txtEmail.setText(nh.getEmail());
        txtGhiChu.setText(nh.getGhiChu());
    }
    
      NguoiHoc getForm(){
        NguoiHoc nh = new NguoiHoc();
        nh.setMaNH(txtMaNH.getText());
        nh.setHoTen(txtHoTenNH.getText());
        nh.setGioiTinh(rdoNam.isSelected());
        nh.setNgaySinh(XDate.toDate(txtNgaySinh.getText(),"dd/MM/yyyy"));
        nh.setDienThoai(txtSDT.getText());
        nh.setEmail(txtEmail.getText());
        nh.setGhiChu(txtGhiChu.getText());
        nh.setMaNV(Auth.user.getMaNV());
        nh.setNgayDK(new Date());
        return nh;
        
    }
    
     private void first() {
        this.row=0;
        this.edit();
    }

    private void prev() {
        if(this.row>0){
            this.row--;
            this.edit();
        }
    }

    private void next() {
        if(this.row<tblNguoiHoc.getRowCount()-1){
            this.row++;
            this.edit();
        }
    }

    private void last() {
        this.row = tblNguoiHoc.getRowCount()-1;
        this.edit();
    }

    private void edit() {
        String manh = (String)tblNguoiHoc.getValueAt(this.row, 0);
        NguoiHoc nh = dao.selectById(manh);
        this.setForm(nh);
        TabbedPaneNH.setSelectedIndex(0);
        this.updateStatus();
    }

    private void insert() {
        NguoiHoc nh = getForm();
        if(nh.getMaNH().equals("")){
            MsgBox.alert(this, "Bạn chưa nhập mã người học!");
            txtMaNH.requestFocus();
        }else if(nh.getMaNH().length()>7){
            MsgBox.alert(this, "Mã người học phải >7 kí tự!");
            txtMaNH.requestFocus();
        }else if(nh.getHoTen().equals("")){
            MsgBox.alert(this, "Bạn chưa nhập họ và tên người học!");
            txtHoTenNH.requestFocus();
        }else if(nh.getDienThoai().equals("")){
            MsgBox.alert(this, "Bạn chưa nhập số điện thoại!");
            txtSDT.requestFocus();
        }else if(nh.getEmail().equals("")){
            MsgBox.alert(this, "Bạn chưa nhập email!");
            txtEmail.requestFocus();
        }else if(nh.getNgaySinh().equals("")){
            MsgBox.alert(this, "Bạn chưa nhập ngày sinh của người học!");
            txtNgaySinh.requestFocus();
        }
        else{
          try {
            dao.insert(nh);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this,"Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại, Vui lòng kiểm tra dữ liệu nhập vào!");
        }  
        }
        
        
    }

    private void update() {
        NguoiHoc nh =getForm();
        try {
                dao.update(nh);
                this.fillTable();
                MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    private void delete() {
         if(!Auth.isManager()){// nếu ko phải truong phong ko cho xoa
            MsgBox.alert(this,"Bạn không có quyền xóa người học!");
        }else{  
             String manh = txtMaNH.getText();
             if(MsgBox.confirm(this,"Bạn thực sự muốn xóa người học này?")){
                try {
                    dao.delete(manh);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this,"Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }
       private void clearForm() {
        NguoiHoc nh = new NguoiHoc();
        nh.setMaNV(Auth.user.getMaNV());
        nh.setNgayDK(new Date());
        this.setForm(nh);
         this.row = -1;
         this.updateStatus();
    }
    
    }

